---
- name: Install brew packages
  homebrew: name={{ item }} state=present
  with_items:
    - ansible
    - arp-scan
    - awscli
    - bash-completion
    - fortune
    - git
    - hub
    - nginx
    - openssl
    - python
    - tree
    - vim
    - wget

- name: Install casks
  homebrew_cask: name={{ item }} state=present
  with_items:
    - adium
    - bartender
    - bettertouchtool
    - firefox
    - flux
    - google-chrome
    - grandperspective
    - iterm2
    - menumeters
    - slack
    - transmission
    - vagrant
    - virtualbox
